### ISSUE TITLE
License seems a bit scary

### ISSUE THREAD

**Issue by ranaya-formant** [maciejhirsz/kobold#32]
Maybe add an explanation at the bottom of your README that explains how using an LGPL library in rust affects your code you build?

**Comment by mbaulch** [comment]
I am not a lawyer, though my understanding is that the implications of the LGPL mean that any crate published under such a license makes it impractical to use in most commercial contexts. 

A somewhat detailed discussion about this issue can be found here:
https://github.com/rpm-software-management/librpm.rs/issues/21

**Comment by maciejhirsz** [comment]
It's likely I'll change the license next release. I quite like LGPL in spirit, except for the emphasis on dynamic linking to keep the library separate, which is impractical in Rust.

It is important to me that any forks or changes to Kobold itself remain open source, which something like MIT doesn't necessarily protect, but I also don't want to force everything built with Kobold to be open source. IANAL either, happy to get suggestions.

**Comment by mbaulch** [comment]
I think that all sounds very reasonable.

In the link I posted above, one commenter [made a convincing case](https://github.com/rpm-software-management/librpm.rs/issues/21#issuecomment-796732760) for the [MPLv2](https://www.mozilla.org/en-US/MPL/2.0/FAQ/). I may have overlooked something, though on first reading it appears this license meets your requirements.

Anyway, thanks for all the hard work you've put into this crate! :)

**Comment by maciejhirsz** [comment]
Yeah, I went and consulted ChatGPT (I can't believe I'm saying this), and MPL hits the mark!

**Comment by maciejhirsz** [comment]
Closing now that change to MPL has been merged.
