### ISSUE TITLE
Update `bind!` documentation to show example of equivalent techniques using `state`

### ISSUE THREAD

**Issue by ltfschoen** [maciejhirsz/kobold#54]
In the docs [here](https://docs.rs/kobold/latest/kobold/macro.bind.html), it shows how to use `bind!`

In the invoice example, I wanted an editable input field, and I wanted to be able to load from a file (like your csv example), and populate the editable fields value with a value from the file, and still have that input field being editable (like your csv example).

But I there were different techniques being used in the examples. After I got it to work I found that the following:
```rust
#[component]
fn MyView<'a>(state: &'a Hook<State>) -> impl View + 'a {
    let ondblclick = state.bind(move |s, _| s.entry.editing = true);
    view! {
        <div {ondblclick} >click to edit</div>
    }
}
```
is equivalent to this:
```rust
#[component]
fn MyView<'a>(state: &'a Hook<State>) -> impl View + 'a {
    bind! { state:
        let ondblclick = move |_| state.editing = true;
    }
    view! {
        <div {ondblclick} >click to edit</div>
    }
}
```

So in the examples the following:
```rust
bind! { state:
    let onchange = move |e: Event<InputElement>| {
        state.table.rows[0][0] = Text::Owned(e.target().value().into());
        state.editing = false;
    };
}
```
is equivalent to this:
```rust
let onchange = state.bind(move |state, e: Event<InputElement>| {
    state.table.rows[0][0] = Text::Owned(e.target().value().into());
    state.editing = false;
});
```
If I have another look at the docs it does show how it's desugered, but it wasn't immediately obvious to me.
Could it be beneficial to update the [bind](https://docs.rs/kobold/latest/kobold/macro.bind.html#) docs to show an example with both options using the `state`?

**Comment by ltfschoen** [comment]
After a bit more reading i found this method [`bind`](https://docs.rs/kobold/latest/kobold/stateful/struct.Hook.html#method.bind), which is the one I used to be able to do `state.bind` :)

**Comment by maciejhirsz** [comment]
> Why is the `bind!` macro recommended over using this `bind` method?

Because I estimate that the macro is more ergonomic and at this point more stable (less likely to have breaking changes in the future) than the method. For that reason I also prefer to keep the documentation focused on the `bind!` macro.

Down the line I'd like to make that macro unnecessary by basically auto-binding event handlers in components, pushing **Kobold** more towards a proper DSL (which it already kind of is).
